--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make-Failearly
version:             1.02
abstract:            CPAN Test Dummy for CPAN.pm
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
